pipeline {
    agent any
    tools {
        maven 'mvn 3.5.0'
    }
    stages {
        stage ('Build Maven'){
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/RadBile2022/devops-automation.git']])
                sh 'mvn clean install'
            }
        }
        stage ('Test'){
            steps {
                script {
                    sh 'mvn test'
                }
            }
        }
        stage('Deploy') { 
            steps {
                sh './jenkins/deliver.sh' 
                input message: 'Sudah selesai menggunakan Java App? (Klik "Proceed" untuk mengakhiri)' 
                sh './jenkins/kill.sh' 
            }
        }
           
    }
}
